
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exp9_1(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);


//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [9:0]h_addr;
wire [9:0]v_addr;
reg [23:0]vga_data = 24'hffffff;

clkgen #(25000000) my_vgaclk(CLOCK_50,SW[0],1'b1,VGA_CLK);
vga_ctrl my_vga(VGA_CLK,SW[0],vga_data,h_addr,v_addr,
	VGA_HS,VGA_VS,VGA_BLANK_N,VGA_R,VGA_G,VGA_B);

//=======================================================
//  Structural coding
//=======================================================

always @(v_addr) begin
	if (v_addr <= 69) vga_data <= 24'hff0000;
	else if (v_addr <= 137) vga_data <= 24'hffaa00;
	else if (v_addr <= 206) vga_data <= 24'hffff00;
	else if (v_addr <= 274) vga_data <= 24'h00ff00;
	else if (v_addr <= 343) vga_data <= 24'h00ffff;
	else if (v_addr <= 411) vga_data <= 24'h0000ff;
	else if (v_addr <= 480) vga_data <= 24'hff00ff;
	else vga_data <= 24'hffffff;
end

endmodule
