
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exp9_2(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [9:0]h_addr;
wire [9:0]v_addr;
reg [23:0]vga_data = 24'hffffff;
reg [18:0]addr = 19'h0;
wire [11:0]out_data;


clkgen #(25000000) my_vgaclk(CLOCK_50,SW[0],1'b1,VGA_CLK);
picture pic(addr,CLOCK_50,out_data);
vga_ctrl my_vga(VGA_CLK,SW[0],vga_data,h_addr,v_addr,
	VGA_HS,VGA_VS,VGA_BLANK_N,VGA_R,VGA_G,VGA_B);

//=======================================================
//  Structural coding
//=======================================================

assign VGA_SYNC_N = 1'b0;

always @(v_addr or h_addr) begin
    addr = v_addr + (h_addr - 1) * 512 - 1;
    vga_data[3:0] <= 4'b0;
    vga_data[7:4] <= out_data[3:0];
    vga_data[11:8] <= 4'b0;
    vga_data[15:12] <= out_data[7:4];
    vga_data[19:16] <= 4'b0;
    vga_data[23:20] <= out_data[11:8];
end

endmodule

